# .github/workflows/deploy-base.yml
name: Deploy Graph on Base Mainnet

on:
  workflow_call:
    secrets:
      DEPLOYMENT_THEGRAPH_SECRET:
        required: true
    inputs:
      SUBGRAPH_SLUG:
        description: Specify a subgraph name
        required: false
        type: string
        default: chain-wiki-base
      VERSION_LABEL:
        description: Specify the version label for the deployment
        required: false
        type: string
        default: v0.0.1

  workflow_dispatch:
    inputs:
      SUBGRAPH_SLUG:
        description: Are you going to deploy a Base Mainnet version?
        required: true
        type: choice
        default: chain-wiki-base
        options:
          - chain-wiki-base
      VERSION_LABEL:
        description: Specify the version label for the deployment
        required: true
        type: string
        default: v0.0.1

jobs:
  deploy-base:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Build full
        env:
          NETWORK: base
        run: yarn build:full

      - name: Lint
        run: yarn lint

      - name: Deploy
        env:
          SUBGRAPH_SLUG: ${{ inputs.SUBGRAPH_SLUG }}
          VERSION_LABEL: ${{ inputs.VERSION_LABEL }}
          NETWORK: base
        run: |
          export DEPLOY_KEY="${{ secrets.DEPLOYMENT_THEGRAPH_SECRET }}"
          yarn deploy:thegraph
